"""Modelos e servicos de dominio."""

from roteirizacao.domain.enums import (
    ClasseOperacional,
    ClassePlanejamento,
    Criticidade,
    RegraCompatibilidade,
    SeveridadeContratual,
    SeveridadeEvento,
    StatusCancelamento,
    StatusExecucaoPlanejamento,
    StatusOrdem,
    TipoEventoAuditoria,
    TipoPonto,
    TipoServico,
    TipoViatura,
)
from roteirizacao.domain.events import ErroContrato, ErroValidacao, EventoAuditoria
from roteirizacao.domain.models import (
    Base,
    BaseBruta,
    CompatibilidadeOperacional,
    Coordenada,
    JanelaTempo,
    MetadadoIngestao,
    MetadadoRastreabilidade,
    Ordem,
    OrdemBruta,
    OrdemClassificada,
    Ponto,
    PontoBruto,
    Viatura,
    ViaturaBruta,
)
from roteirizacao.domain.services import ContextoExecucao

__all__ = [
    "Base",
    "BaseBruta",
    "ClasseOperacional",
    "ClassePlanejamento",
    "CompatibilidadeOperacional",
    "ContextoExecucao",
    "Coordenada",
    "Criticidade",
    "ErroContrato",
    "ErroValidacao",
    "EventoAuditoria",
    "JanelaTempo",
    "MetadadoIngestao",
    "MetadadoRastreabilidade",
    "Ordem",
    "OrdemBruta",
    "OrdemClassificada",
    "Ponto",
    "PontoBruto",
    "RegraCompatibilidade",
    "SeveridadeContratual",
    "SeveridadeEvento",
    "StatusCancelamento",
    "StatusExecucaoPlanejamento",
    "StatusOrdem",
    "TipoEventoAuditoria",
    "TipoPonto",
    "TipoServico",
    "TipoViatura",
    "Viatura",
    "ViaturaBruta",
]
