"""Modelos e servicos de dominio."""

from roteirizacao.domain.enums import (
    ClasseOperacional,
    ClassePlanejamento,
    Criticidade,
    RegraCompatibilidade,
    SeveridadeContratual,
    SeveridadeEvento,
    StatusCancelamento,
    StatusExecucaoPlanejamento,
    StatusOrdem,
    TipoEventoAuditoria,
    TipoPonto,
    TipoServico,
    TipoViatura,
)
from roteirizacao.domain.events import ErroContrato, ErroValidacao, EventoAuditoria
from roteirizacao.domain.logistics import MatrizLogistica, TrechoLogistico
from roteirizacao.domain.models import (
    Base,
    BaseBruta,
    CompatibilidadeOperacional,
    Coordenada,
    JanelaTempo,
    MetadadoIngestao,
    MetadadoRastreabilidade,
    Ordem,
    OrdemBruta,
    OrdemClassificada,
    Ponto,
    PontoBruto,
    Viatura,
    ViaturaBruta,
)
from roteirizacao.domain.optimization import (
    DepositoRoteirizacao,
    InstanciaRoteirizacaoBase,
    NoRoteirizacao,
    PenalidadeRoteirizacao,
    RestricaoElegibilidade,
    VeiculoRoteirizacao,
)
from roteirizacao.domain.results import (
    KpiGerencial,
    KpiOperacional,
    LogPlanejamento,
    MotivoInviabilidade,
    OrdemNaoAtendida,
    ParadaPlanejada,
    ResumoOperacional,
    ResultadoPlanejamento,
    RotaPlanejada,
)
from roteirizacao.domain.services import ContextoExecucao

__all__ = [
    "Base",
    "BaseBruta",
    "ClasseOperacional",
    "ClassePlanejamento",
    "CompatibilidadeOperacional",
    "ContextoExecucao",
    "Coordenada",
    "Criticidade",
    "DepositoRoteirizacao",
    "ErroContrato",
    "ErroValidacao",
    "EventoAuditoria",
    "InstanciaRoteirizacaoBase",
    "JanelaTempo",
    "KpiGerencial",
    "KpiOperacional",
    "LogPlanejamento",
    "MatrizLogistica",
    "MetadadoIngestao",
    "MetadadoRastreabilidade",
    "MotivoInviabilidade",
    "NoRoteirizacao",
    "Ordem",
    "OrdemBruta",
    "OrdemClassificada",
    "OrdemNaoAtendida",
    "ParadaPlanejada",
    "PenalidadeRoteirizacao",
    "Ponto",
    "PontoBruto",
    "RegraCompatibilidade",
    "RestricaoElegibilidade",
    "ResultadoPlanejamento",
    "ResumoOperacional",
    "RotaPlanejada",
    "SeveridadeContratual",
    "SeveridadeEvento",
    "StatusCancelamento",
    "StatusExecucaoPlanejamento",
    "StatusOrdem",
    "TipoEventoAuditoria",
    "TipoPonto",
    "TipoServico",
    "TipoViatura",
    "TrechoLogistico",
    "VeiculoRoteirizacao",
    "Viatura",
    "ViaturaBruta",
]
