"""Pacote principal do projeto de roteirizacao de numerario."""

from roteirizacao.application import (
    ClassPostProcessingResult,
    FallbackLogisticsMatrixProvider,
    FileSystemSnapshotRepository,
    InstanceBuildResult,
    JsonFileLogisticsSnapshotSource,
    LogisticsMatrixBuilder,
    LogisticsMatrixProvider,
    LogisticsSnapshotMaterializer,
    LogisticsSnapshotSource,
    OptimizationInstanceBuilder,
    PersistedSnapshotLogisticsMatrixProvider,
    PlanningExecutor,
    PostProcessingResult,
    PreparationPipeline,
    PreparationResult,
    RoutePostProcessor,
    SnapshotCoverageError,
    SnapshotMaterializationResult,
    SnapshotUnavailableError,
    SolverExecutionArtifact,
)
from roteirizacao.optimization import PyVRPAdapter, SolverAdapter

__all__ = [
    "ClassPostProcessingResult",
    "FallbackLogisticsMatrixProvider",
    "FileSystemSnapshotRepository",
    "InstanceBuildResult",
    "JsonFileLogisticsSnapshotSource",
    "LogisticsMatrixBuilder",
    "LogisticsMatrixProvider",
    "LogisticsSnapshotMaterializer",
    "LogisticsSnapshotSource",
    "OptimizationInstanceBuilder",
    "PersistedSnapshotLogisticsMatrixProvider",
    "PlanningExecutor",
    "PostProcessingResult",
    "PreparationPipeline",
    "PreparationResult",
    "PyVRPAdapter",
    "RoutePostProcessor",
    "SnapshotCoverageError",
    "SnapshotMaterializationResult",
    "SnapshotUnavailableError",
    "SolverAdapter",
    "SolverExecutionArtifact",
]
